#!/usr/bin/env nextflow
nextflow.enable.dsl=2

// ================================================================================
//  CANOES MODULE
// ================================================================================

// Define parameters for the workflow
params.ref    = ''
params.probes = ''
params.outdir = 'results'

ref    = file(params.ref, type: 'file')
probes = file(params.probes, type: 'file')
outdir = file(params.outdir, type: 'dir')

// Define the list of chromosomes to process
chromosomes = ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", 
               "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", 
               "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]

// Process to calculate GC content for each chromosome
process calcGC_CANOES {
    tag { "${chr}" }
    label 'gatk'
    publishDir "${outdir}/out_CANOES/${chr}", mode: 'copy', overwrite: true
    
    input:
    each chr
    
    output:
    tuple val("${chr}"), path("${chr}_gc.txt"), emit: chr_gc_content 

    script:
    mem = task.memory.toGiga() - 4
    
    """
    grep ^"${chr}	" ${probes} > ${chr}_probes_sanger.bed

    gatk --java-options "-XX:+UseSerialGC -Xss456k -Xms2g -Xmx${mem}g" \
        AnnotateIntervals \
        -R ${ref} \
        -L ${chr}_probes_sanger.bed \
        --interval-merging-rule OVERLAPPING_ONLY \
        -O ${chr}_gc.tmp

    grep ^"${chr}" ${chr}_gc.tmp | awk '{ print \$1":"\$2"-"\$3"\t"\$4 }' > ${chr}_gc.txt
    """
}

// Process to generate read counts using Bedtools
process genReadCounts {
    tag { "${chr}" }
    label 'bedtools'
    publishDir "${outdir}/out_CANOES/${chr}", mode: 'copy', overwrite: true
    
    input:
    path(bam_list)
    each chr

    output:
    tuple val("${chr}"), path("${chr}_canoes_reads.txt"), path("${chr}_sample_list"), emit: chr_reads_cov
    
    script:
    """
    ## CREATE A SORTED LIST OF BAM FILES FOR BEDTOOLS
    sort ${bam_list} > bam_list_sorted.txt

    ## SUBSET THE PROBES FOR A PARTICULAR CHROMOSOME
    grep ^"${chr}	" ${probes} > ${chr}_probes_sanger.bed

    ## CREATE SAMPLE LIST FILE FOR CANOES IN R
    while read line
    do
        echo `basename \$line` | sed 's/.bam//'
    done < bam_list_sorted.txt > ${chr}_sample_list

    ## RUN BEDTOOLS FOR THE CHROMOSOME
    bedtools multicov -bams `cat bam_list_sorted.txt` -bed ${chr}_probes_sanger.bed -q 20 > ${chr}_canoes_reads.txt
    """
}

// Process to run the CANOES algorithm
process runCANOES {
    tag { "${chr}" }
    label 'canoes'
    memory '5 GB'
    publishDir "${outdir}/out_CANOES/${chr}", mode: 'copy', overwrite: true
    
    input:
    tuple val(chr), path(canoes_reads), path(sample_list), path(gc_content)

    output:
    tuple val(chr), path("${chr}_CNVs_pass.csv"), emit: chr_cnvs_pass
    tuple val(chr), path("${chr}_CNVs_fail.csv"), emit: chr_cnvs_fail
    tuple val(chr), path("${chr}_xcnvs.RData"), emit: chr_cnvs_rdata
    tuple val(chr), path("${chr}_CNV_genotype"), emit: chr_cnvs_geno
    tuple val(chr), path("${chr}_CNV_plots"), emit: chr_cnvs_plots
    
    script:
    """
    sed 's/chr//g; /^X/d; /^Y/d' ${canoes_reads} > ${chr}_canoes_reads_new.txt
    sed 's/chr//g; /^X/d; /^Y/d' ${gc_content} > ${chr}_gc_new.txt 
    
    run_canoes.R ${chr}_gc_new.txt ${chr}_canoes_reads_new.txt ${sample_list}
    """
}

// Process to filter CNVs generated by CANOES
process filterCANOESCNVs {
    tag { "ALL_CNVs" }
    label 'canoes'
    publishDir "${outdir}/out_CANOES", mode: 'copy', overwrite: true
    
    input:
    path(cnvs)
    
    output:
    path("Sample_CNVs.csv"), emit: all_cnvs
    path("Sample_CNVs_filtered.csv"), emit: filtered_cnvs
    
    script:
    """
    grep --no-filename SAMPLE *_CNVs_pass.csv | uniq > Sample_CNVs.csv
    grep -v --no-filename SAMPLE *_CNVs_pass.csv | sort -k1,1 -k3g,3 >> Sample_CNVs.csv
    head -1 Sample_CNVs.csv > Sample_CNVs_filtered.csv
    awk 'NR>1 && (\$10>=80) && (\$10!="NA") && (\$4>=100) { print }' Sample_CNVs.csv >> Sample_CNVs_filtered.csv
    """
}

// Process to convert the filtered CANOES output to VCF format
process convertCanoesToVcf {
    tag { "CSV_TO_VCF" }
    label 'canoes|R'
    publishDir "${outdir}/out_CANOES/vcfs", mode: 'copy', overwrite: true

    input:
    path(filtered_csv)
    path(sample_list)
    path(fai)

    output:
    path("*_CANOES_output.vcf"), emit: vcfs

    script:
    """
    canoes_csv_to_vcf.py \\ 
        --input_file ${filtered_csv} \\ 
        --sample_file ${sample_list} \\ 
        --output_dir . \\ 
        --fai_file ${fai}
    """
}

// Process to compress, sort, index, and annotate each CANOES VCF with TOOL=CANOES
process BGZIP_SORT_INDEX_VCF {
    tag "${vcf_file.simpleName}"
    label 'canoes|R'
    publishDir "${outdir}/out_CANOES/vcfs", mode: 'copy', overwrite: true

    input:
    path vcf_file

    output:
    path("*.sorted.vcf.gz"),     emit: sorted_vcf
    path("*.sorted.vcf.gz.tbi"), emit: sorted_vcf_index

    script:
    def sample_name = vcf_file.simpleName
    def sorted_gz   = "${sample_name}.sorted.vcf.gz"
    """
    # Create extra header line for the TOOL INFO field
    printf '##INFO=<ID=TOOL,Number=1,Type=String,Description="Calling tool">\\n' > extra_header.txt

    # Build a BED annotation file with TOOL=CANOES for every variant
    bcftools query -f '%CHROM\\t%POS0\\t%END\\n' ${vcf_file} | \\
        awk 'BEGIN{OFS="\\t"} {print \$1, \$2, \$3, "CANOES"}' | \\
        bgzip -c > ${sample_name}_tool_annot.bed.gz
    tabix -p bed ${sample_name}_tool_annot.bed.gz

    # Annotate the VCF with TOOL=CANOES in the INFO field
    bcftools annotate \\
        -a ${sample_name}_tool_annot.bed.gz \\
        -c CHROM,FROM,TO,INFO/TOOL \\
        -h extra_header.txt \\
        ${vcf_file} \\
        -O v -o ${sample_name}_annotated.vcf

    # Compress the annotated VCF with bgzip
    bgzip -c ${sample_name}_annotated.vcf > ${sample_name}_annotated.vcf.gz

    # Sort the compressed VCF
    bcftools sort ${sample_name}_annotated.vcf.gz -o ${sorted_gz} -O z

    # Index the sorted VCF
    tabix -p vcf ${sorted_gz}

    # Remove intermediate files
    rm -f ${sample_name}_tool_annot.bed.gz ${sample_name}_tool_annot.bed.gz.tbi \\
          ${sample_name}_annotated.vcf ${sample_name}_annotated.vcf.gz
    """
}

// =====================================================================================
// SUB-WORKFLOW TO CHAIN THE PROCESSES TOGETHER
// =====================================================================================

// Execute the pipeline
workflow CANOES {
    take:
    bam_list_ch   // path: file containing BAM file paths, one per line
    fai_ch        // path: reference FASTA index (.fai)
    chroms_ch     // channel: chromosome names to process

    main:
    // Step 1: Calculate GC content per chromosome
    calcGC_CANOES(chroms_ch)

    // Step 2: Generate per-chromosome read counts
    genReadCounts(bam_list_ch, chroms_ch)

    // Step 3: Join read-counts and GC content by chromosome, then run CANOES
    canoes_input_ch = genReadCounts.out.chr_reads_cov
        .join(calcGC_CANOES.out.chr_gc_content, by: 0)

    runCANOES(canoes_input_ch)

    // Step 4: Collect all per-chromosome pass-CNV files and filter
    all_cnvs_ch = runCANOES.out.chr_cnvs_pass
        .map { chr, cnv_file -> cnv_file }
        .collect()

    filterCANOESCNVs(all_cnvs_ch)

    // Step 5: Reuse sample list from the first genReadCounts output
    sample_list_ch = genReadCounts.out.chr_reads_cov
        .first()
        .map { chr, reads, sample_list -> sample_list }

    convertCanoesToVcf(
        filterCANOESCNVs.out.filtered_cnvs,
        sample_list_ch,
        fai_ch
    )

    // Step 6: Compress, sort, index, and annotate each VCF with TOOL=CANOES
    BGZIP_SORT_INDEX_VCF(convertCanoesToVcf.out.vcfs)

    emit:
    sorted_vcf       = BGZIP_SORT_INDEX_VCF.out.sorted_vcf
    sorted_vcf_index = BGZIP_SORT_INDEX_VCF.out.sorted_vcf_index
}


